import { useTheme } from '../contexts/ThemeContext';

const sections = [
  {
    title: 'What Temple Is',
    body: `Temple is a reflective AI tool designed to support introspection and self-exploration. It is not a substitute for professional mental health support, medical advice, therapy, or crisis services. If you are experiencing a mental health emergency, please contact a qualified professional or emergency service immediately.`,
  },
  {
    title: 'Use of Service',
    body: `You must be at least 18 years of age to use Temple. Each person may maintain only one account. Automated access, scraping, or any form of programmatic interaction with Temple is prohibited without explicit written permission.`,
  },
  {
    title: 'Prohibited Conduct',
    body: `You may not use Temple to harm, harass, or endanger others. Attempts to manipulate, reverse-engineer, or extract the underlying logic of the AI are prohibited. You may not share another person's private or sensitive information through the service.`,
  },
  {
    title: 'Intellectual Property',
    body: `Temple's design, response format, visual identity, and interface are proprietary and protected by applicable intellectual property laws. Conversation content you create within Temple belongs to you. Temple does not claim ownership over your words.`,
  },
  {
    title: 'Disclaimers',
    body: `Temple is provided on an as-is basis without warranties of any kind, whether express or implied. Responses generated by Temple are reflective in nature and do not constitute professional advice of any kind, including but not limited to medical, legal, financial, or psychological advice.`,
  },
  {
    title: 'Limitation of Liability',
    body: `Temple and its creators are not liable for any decisions, actions, or outcomes resulting from the use of this service or its responses. You acknowledge that you use Temple at your own discretion and assume full responsibility for how you interpret and act upon its output.`,
  },
  {
    title: 'Governing Law',
    body: `These terms are governed by and construed in accordance with the laws of the State of California, United States, without regard to conflict of law principles.`,
  },
  {
    title: 'Changes to These Terms',
    body: `Temple may update these terms from time to time. When changes are made, users will be notified by email. Continued use of the service after notification constitutes acceptance of the updated terms.`,
  },
  {
    title: 'Contact',
    body: `For legal inquiries or questions about these terms, please reach out to legal@temple.app.`,
  },
];

export default function TermsOfService() {
  const { theme } = useTheme();
  const isDark = theme !== 'light';

  const textColor = isDark ? 'text-white' : 'text-gray-900';
  const mutedColor = isDark ? 'text-[rgba(255,255,255,0.4)]' : 'text-[rgba(0,0,0,0.4)]';
  const bodyOpacity = 'opacity-75';

  return (
    <div className="flex-1 flex justify-center px-6 md:px-10">
      <div className="w-full max-w-[680px] pt-16 pb-20">
        {/* Header */}
        <h1 className={`font-['Playfair_Display',_serif] text-3xl md:text-4xl font-light ${textColor}`}>
          Terms of Service
        </h1>
        <p className={`font-['Inter',_sans-serif] text-xs ${mutedColor} mt-2`}>
          Last updated — March 12, 2026
        </p>

        {/* Body */}
        <div className="mt-12 flex flex-col gap-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className={`font-['Inter',_sans-serif] text-[0.65rem] uppercase tracking-[0.15em] ${mutedColor} mb-3`}>
                {section.title}
              </h2>
              <p className={`font-['Inter',_sans-serif] text-[0.85rem] font-light leading-[1.85] ${textColor} ${bodyOpacity}`}>
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
