import { useTheme } from '../contexts/ThemeContext';

const sections = [
  {
    title: 'Purpose',
    body: `Temple is designed for personal reflection, inner clarity, and conscious exploration. By using Temple you agree to use it with that intent.`,
  },
  {
    title: 'Prohibited Use',
    body: `You may not use Temple to generate harmful, abusive, or illegal content. Attempts to manipulate or jailbreak the AI are prohibited. You may not scrape, reproduce, or resell Temple's responses. You may not impersonate others or create false identities.`,
  },
  {
    title: 'Disclaimer',
    body: `Temple's responses are generated by AI and are not a substitute for professional medical, legal, psychological, or financial advice.`,
  },
  {
    title: 'Enforcement',
    body: `We reserve the right to suspend accounts that violate these terms.`,
  },
  {
    title: 'Contact',
    body: `Questions? reach@temple.ai`,
  },
];

export default function UsagePolicy() {
  const { theme } = useTheme();
  const isDark = theme !== 'light';

  const textColor = isDark ? 'text-white' : 'text-gray-900';
  const mutedColor = isDark ? 'text-[rgba(255,255,255,0.4)]' : 'text-[rgba(0,0,0,0.4)]';
  const bodyOpacity = 'opacity-75';

  return (
    <div className="flex-1 flex justify-center px-6 md:px-10">
      <div className="w-full max-w-[680px] pt-16 pb-20">
        <h1 className={`font-['Playfair_Display',_serif] text-3xl md:text-4xl font-light ${textColor}`}>
          Usage Policy
        </h1>
        <p className={`font-['Inter',_sans-serif] text-xs ${mutedColor} mt-2`}>
          Last updated — March 2026
        </p>

        <div className="mt-12 flex flex-col gap-10">
          {sections.map((section) => (
            <div key={section.title}>
              <h2 className={`font-['Inter',_sans-serif] text-[0.65rem] uppercase tracking-[0.15em] ${mutedColor} mb-3`}>
                {section.title}
              </h2>
              <p className={`font-['Inter',_sans-serif] text-[0.85rem] font-light leading-[1.85] ${textColor} ${bodyOpacity}`}>
                {section.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
